version: 2.1

orbs:
  node: circleci/node@5

executors:
  node-executor:
    docker:
      - image: circleci/node:16

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Run lint
          command: npm run lint

workflows:
  version: 2
  my-workflow:
    jobs:
      - build
