version: 2.1
orbs:
  node: circleci/node@5

workflows:
  my-workflow:
    jobs:
      - build

jobs:
  build:
    steps:
      - checkout
      - run:
          name: Clean npm cache
          command: npm cache clean --force
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Verify Node.js and npm versions
          command: node -v && npm -v
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Run lint
          command: npm run lint
